stages:
  - compile
  - test

build:
  stage: compile
  image: golang:1.18
  script:
    - go get -d -v
    - go build -o bin/my-url-shortener -v .

test:
  stage: test
  image: golang:1.18
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
    - golangci-lint run
    - go test
