image: "artifactory-gojek.golabs.io:6555/cx-go:1.18"

services:
  - name: artifactory-gojek.golabs.io:6555/grokzen/redis-cluster:latest
    alias: redis-cluster

stages:
  - compile
  - test

build:
  stage: compile
  script:
    - make ci

test:
  stage: test
  script:
    - make test
    - make clean
