image: "artifactory-gojek.golabs.io:6555/cx-go:1.18"

variables:
  GOPRIVATE: "source.golabs.io/*"
  STORAGE_HOST: redis-cluster

services:
  - name: artifactory-gojek.golabs.io:6555/grokzen/redis-cluster:latest
    alias: redis-cluster

stages:
  - compile
  - test

build:
  stage: compile
  before_script:
    - git config --global url."https://source.golabs.io/".insteadOf git@source.golabs.io":"
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:$CI_BUILD_TOKEN@source.golabs.io" > ~/.git-credentials
  script:
    - make ci

test:
  stage: test
  before_script:
    - git config --global url."https://source.golabs.io/".insteadOf git@source.golabs.io":"
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:$CI_BUILD_TOKEN@source.golabs.io" > ~/.git-credentials
  script:
    - make test
    - make clean
