stages:
  - compile
  - test

build:
  stage: compile
  image: golang:1.18
  script:
    - go get -d -v
    - go build -o bin/my-url-shortener -v .

test:
  stage: test
  image: golang:1.18
  script:
    - go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0 run
    - go test
