image: "artifactory-gojek.golabs.io:6555/cx-go:1.18"

stages:
  - compile
  - test

build:
  stage: compile
  script:
    - apt-get update && apt-get install redis
    - make ci

test:
  stage: test
  script:
    - make test
    - make clean
