image: "artifactory-gojek.golabs.io:6555/cx-go:1.18"

stages:
  - compile
  - test

build:
  stage: compile
  services:
    - name: artifactory-gojek.golabs.io:6555/grokzen/redis-cluster:latest
      alias: redis-cluster
  script:
    - make ci

test:
  stage: test
  script:
    - make test
    - make clean
