image: "artifactory-gojek.golabs.io:6555/cx-go:1.18"

stages:
  - compile
  - test

build:
  stage: compile
  services:
    redis:
      image: artifactory-gojek.golabs.io:6555/grokzen/redis-cluster:latest
      ports:
        - "6379:6379"
  script:
    - make ci

test:
  stage: test
  script:
    - make test
    - make clean
